"""Oracle MNCDEV의 최초 프로젝트 계정과 핵심 테이블을 생성한다.

이 모듈은 비밀번호를 보관하지 않는다. ADMIN과 MNC_APP 비밀번호는 실행
스크립트가 메모리에서만 받아 연결에 사용한다.
"""

from __future__ import annotations

import re
from typing import Any


APP_SCHEMA = "MNC_APP"
READ_ROLE = "MNC_READ_ROLE"
ETL_ROLE = "MNC_ETL_ROLE"

_IDENTIFIER_PATTERN = re.compile(r"^[A-Z][A-Z0-9_$#]{0,29}$")


TABLE_DDL: dict[str, str] = {
    "META_SOURCE_FILE": """
        CREATE TABLE META_SOURCE_FILE (
            source_file_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            source_name VARCHAR2(255) NOT NULL,
            object_storage_uri VARCHAR2(1000),
            sha256 CHAR(64) NOT NULL,
            file_size_bytes NUMBER(19) NOT NULL,
            reference_year NUMBER(4),
            source_type VARCHAR2(30) NOT NULL,
            sensitivity_level VARCHAR2(30) DEFAULT 'INTERNAL' NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_META_FILE PRIMARY KEY (source_file_id),
            CONSTRAINT UQ_META_FILE_SHA UNIQUE (sha256),
            CONSTRAINT CK_META_FILE_SIZE CHECK (file_size_bytes >= 0)
        )
    """,
    "META_ETL_RUN": """
        CREATE TABLE META_ETL_RUN (
            etl_run_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            pipeline_name VARCHAR2(100) NOT NULL,
            code_version VARCHAR2(64),
            started_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            finished_at TIMESTAMP WITH TIME ZONE,
            status VARCHAR2(20) DEFAULT 'RUNNING' NOT NULL,
            input_row_count NUMBER(19),
            output_row_count NUMBER(19),
            warning_count NUMBER(10) DEFAULT 0 NOT NULL,
            error_message CLOB,
            CONSTRAINT PK_ETL_RUN PRIMARY KEY (etl_run_id),
            CONSTRAINT CK_ETL_STATUS CHECK (
                status IN ('RUNNING', 'SUCCESS', 'FAILED', 'WARNING')
            ),
            CONSTRAINT CK_ETL_COUNTS CHECK (
                (input_row_count IS NULL OR input_row_count >= 0)
                AND (output_row_count IS NULL OR output_row_count >= 0)
                AND warning_count >= 0
            )
        )
    """,
    "META_ETL_RUN_INPUT": """
        CREATE TABLE META_ETL_RUN_INPUT (
            etl_run_id NUMBER NOT NULL,
            source_file_id NUMBER NOT NULL,
            input_role VARCHAR2(50) DEFAULT 'PRIMARY' NOT NULL,
            CONSTRAINT PK_ETL_RUN_INPUT PRIMARY KEY (
                etl_run_id, source_file_id, input_role
            ),
            CONSTRAINT FK_RUN_INPUT_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT FK_RUN_INPUT_FILE FOREIGN KEY (source_file_id)
                REFERENCES META_SOURCE_FILE (source_file_id)
        )
    """,
    "DIM_ADMIN_AREA": """
        CREATE TABLE DIM_ADMIN_AREA (
            area_code VARCHAR2(10) NOT NULL,
            area_name VARCHAR2(100) NOT NULL,
            area_level VARCHAR2(10) NOT NULL,
            parent_area_code VARCHAR2(10),
            valid_from DATE NOT NULL,
            valid_to DATE,
            source_reference_year NUMBER(4),
            CONSTRAINT PK_ADMIN_AREA PRIMARY KEY (area_code),
            CONSTRAINT FK_ADMIN_PARENT FOREIGN KEY (parent_area_code)
                REFERENCES DIM_ADMIN_AREA (area_code),
            CONSTRAINT CK_ADMIN_LEVEL CHECK (
                area_level IN ('SIDO', 'GU', 'DONG')
            ),
            CONSTRAINT CK_ADMIN_DATES CHECK (
                valid_to IS NULL OR valid_to >= valid_from
            )
        )
    """,
    "DIM_GRID": """
        CREATE TABLE DIM_GRID (
            grid_cd VARCHAR2(20) NOT NULL,
            dong_code VARCHAR2(10) NOT NULL,
            center_x NUMBER(15, 3) NOT NULL,
            center_y NUMBER(15, 3) NOT NULL,
            grid_cd_500 VARCHAR2(20),
            source_reference_year NUMBER(4) NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_DIM_GRID PRIMARY KEY (grid_cd),
            CONSTRAINT FK_GRID_DONG FOREIGN KEY (dong_code)
                REFERENCES DIM_ADMIN_AREA (area_code)
        )
    """,
    "DIM_CATEGORY": """
        CREATE TABLE DIM_CATEGORY (
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            category_name VARCHAR2(100) NOT NULL,
            display_order NUMBER(5),
            supported_flag CHAR(1) DEFAULT 'Y' NOT NULL,
            valid_from_year NUMBER(4),
            valid_to_year NUMBER(4),
            CONSTRAINT PK_CATEGORY PRIMARY KEY (scheme_code, category_code),
            CONSTRAINT CK_CATEGORY_SUPPORT CHECK (supported_flag IN ('Y', 'N')),
            CONSTRAINT CK_CATEGORY_YEARS CHECK (
                valid_to_year IS NULL
                OR valid_from_year IS NULL
                OR valid_to_year >= valid_from_year
            )
        )
    """,
    "BRIDGE_CATEGORY_MAP": """
        CREATE TABLE BRIDGE_CATEGORY_MAP (
            from_scheme_code VARCHAR2(30) NOT NULL,
            from_category_code VARCHAR2(30) NOT NULL,
            to_scheme_code VARCHAR2(30) NOT NULL,
            to_category_code VARCHAR2(30) NOT NULL,
            mapping_weight NUMBER(12, 10) DEFAULT 1 NOT NULL,
            mapping_status VARCHAR2(30) DEFAULT 'DIRECT' NOT NULL,
            mapping_note VARCHAR2(500),
            CONSTRAINT PK_CATEGORY_MAP PRIMARY KEY (
                from_scheme_code, from_category_code,
                to_scheme_code, to_category_code
            ),
            CONSTRAINT FK_MAP_FROM FOREIGN KEY (
                from_scheme_code, from_category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT FK_MAP_TO FOREIGN KEY (
                to_scheme_code, to_category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT CK_MAP_WEIGHT CHECK (
                mapping_weight > 0 AND mapping_weight <= 1
            )
        )
    """,
    "STG_CARD_USAGE_RAW27": """
        CREATE TABLE STG_CARD_USAGE_RAW27 (
            etl_run_id NUMBER NOT NULL,
            reference_year NUMBER(4) NOT NULL,
            district_name VARCHAR2(100) NOT NULL,
            source_category_name VARCHAR2(100) NOT NULL,
            usage_amount_won NUMBER(19) DEFAULT 0 NOT NULL,
            usage_count NUMBER(19) DEFAULT 0 NOT NULL,
            source_row_no NUMBER(10),
            CONSTRAINT PK_STG_CARD_RAW27 PRIMARY KEY (
                etl_run_id, reference_year,
                district_name, source_category_name
            ),
            CONSTRAINT FK_STG_CARD_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT CK_STG_CARD_VALUES CHECK (
                usage_amount_won >= 0 AND usage_count >= 0
            )
        )
    """,
    "FACT_CARD_GU_YEAR": """
        CREATE TABLE FACT_CARD_GU_YEAR (
            reference_year NUMBER(4) NOT NULL,
            district_code VARCHAR2(10) NOT NULL,
            issued_card_count NUMBER(19),
            user_count NUMBER(19),
            issued_amount_won NUMBER(19),
            budget_amount_won NUMBER(19),
            used_amount_won NUMBER(19) NOT NULL,
            usage_count NUMBER(19) NOT NULL,
            culture_exp_count NUMBER(19),
            culture_exp_pct NUMBER(12, 8),
            etl_run_id NUMBER NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_CARD_GU_YEAR PRIMARY KEY (
                reference_year, district_code
            ),
            CONSTRAINT FK_CARD_YEAR_AREA FOREIGN KEY (district_code)
                REFERENCES DIM_ADMIN_AREA (area_code),
            CONSTRAINT FK_CARD_YEAR_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT CK_CARD_YEAR_VALUES CHECK (
                (issued_card_count IS NULL OR issued_card_count >= 0)
                AND (user_count IS NULL OR user_count >= 0)
                AND (issued_amount_won IS NULL OR issued_amount_won >= 0)
                AND (budget_amount_won IS NULL OR budget_amount_won >= 0)
                AND used_amount_won >= 0
                AND usage_count >= 0
                AND (culture_exp_count IS NULL OR culture_exp_count >= 0)
                AND (culture_exp_pct IS NULL OR culture_exp_pct BETWEEN 0 AND 100)
            )
        )
    """,
    "FACT_CARD_GU_CAT": """
        CREATE TABLE FACT_CARD_GU_CAT (
            reference_year NUMBER(4) NOT NULL,
            district_code VARCHAR2(10) NOT NULL,
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            usage_amount_won NUMBER(19) NOT NULL,
            usage_count NUMBER(19) NOT NULL,
            etl_run_id NUMBER NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_CARD_GU_CAT PRIMARY KEY (
                reference_year, district_code, scheme_code, category_code
            ),
            CONSTRAINT FK_CARD_CAT_AREA FOREIGN KEY (district_code)
                REFERENCES DIM_ADMIN_AREA (area_code),
            CONSTRAINT FK_CARD_CAT_DIM FOREIGN KEY (scheme_code, category_code)
                REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT FK_CARD_CAT_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT CK_CARD_CAT_VALUES CHECK (
                usage_amount_won >= 0 AND usage_count >= 0
            )
        )
    """,
    "FACT_CARD_GU_SEX": """
        CREATE TABLE FACT_CARD_GU_SEX (
            reference_year NUMBER(4) NOT NULL,
            district_code VARCHAR2(10) NOT NULL,
            sex_code CHAR(1) NOT NULL,
            issued_card_count NUMBER(19) NOT NULL,
            used_amount_won NUMBER(19) NOT NULL,
            etl_run_id NUMBER NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_CARD_GU_SEX PRIMARY KEY (
                reference_year, district_code, sex_code
            ),
            CONSTRAINT FK_CARD_SEX_AREA FOREIGN KEY (district_code)
                REFERENCES DIM_ADMIN_AREA (area_code),
            CONSTRAINT FK_CARD_SEX_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT CK_CARD_SEX_CODE CHECK (sex_code IN ('M', 'F')),
            CONSTRAINT CK_CARD_SEX_VALUES CHECK (
                issued_card_count >= 0 AND used_amount_won >= 0
            )
        )
    """,
    "FACT_CARD_GU_AGE": """
        CREATE TABLE FACT_CARD_GU_AGE (
            reference_year NUMBER(4) NOT NULL,
            district_code VARCHAR2(10) NOT NULL,
            age_code VARCHAR2(10) NOT NULL,
            issued_card_count NUMBER(19) NOT NULL,
            etl_run_id NUMBER NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_CARD_GU_AGE PRIMARY KEY (
                reference_year, district_code, age_code
            ),
            CONSTRAINT FK_CARD_AGE_AREA FOREIGN KEY (district_code)
                REFERENCES DIM_ADMIN_AREA (area_code),
            CONSTRAINT FK_CARD_AGE_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT CK_CARD_AGE_VALUES CHECK (issued_card_count >= 0)
        )
    """,
    "DIM_MERCHANT_SNAPSHOT": """
        CREATE TABLE DIM_MERCHANT_SNAPSHOT (
            snapshot_date DATE NOT NULL,
            merchant_key CHAR(64) NOT NULL,
            source_row_no NUMBER(10) NOT NULL,
            merchant_name VARCHAR2(200 CHAR) NOT NULL,
            merchant_type VARCHAR2(50 CHAR),
            category_large VARCHAR2(50 CHAR),
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            category_small VARCHAR2(100 CHAR),
            latitude NUMBER(12, 8),
            longitude NUMBER(12, 8),
            usage_info VARCHAR2(1000 CHAR),
            discount_yn VARCHAR2(20 CHAR),
            discount_detail VARCHAR2(1000 CHAR),
            metro VARCHAR2(50 CHAR),
            district_reported VARCHAR2(100 CHAR),
            district_from_address VARCHAR2(100 CHAR),
            district_code VARCHAR2(10) NOT NULL,
            address VARCHAR2(500 CHAR) NOT NULL,
            modified_at TIMESTAMP,
            registered_at TIMESTAMP,
            keywords VARCHAR2(500 CHAR),
            url VARCHAR2(1000 CHAR),
            registration_actor VARCHAR2(100 CHAR),
            service_types VARCHAR2(200 CHAR),
            phone_payment_detail VARCHAR2(500 CHAR),
            service_detail VARCHAR2(1000 CHAR),
            coordinate_valid CHAR(1) NOT NULL,
            district_mismatch CHAR(1) NOT NULL,
            phone_payment_available CHAR(1) NOT NULL,
            visiting_service_available CHAR(1) NOT NULL,
            disabled_friendly_available CHAR(1) NOT NULL,
            etl_run_id NUMBER NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_MERCHANT_SNAPSHOT PRIMARY KEY (
                etl_run_id, merchant_key
            ),
            CONSTRAINT FK_MERCHANT_AREA FOREIGN KEY (district_code)
                REFERENCES DIM_ADMIN_AREA (area_code),
            CONSTRAINT FK_MERCHANT_CATEGORY FOREIGN KEY (
                scheme_code, category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT FK_MERCHANT_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT CK_MERCHANT_FLAGS CHECK (
                coordinate_valid IN ('Y', 'N')
                AND district_mismatch IN ('Y', 'N')
                AND phone_payment_available IN ('Y', 'N')
                AND visiting_service_available IN ('Y', 'N')
                AND disabled_friendly_available IN ('Y', 'N')
            )
        )
    """,
    "FACT_GRID_TARGET_SEX_AGE": """
        CREATE TABLE FACT_GRID_TARGET_SEX_AGE (
            etl_run_id NUMBER NOT NULL,
            reference_year NUMBER(4) NOT NULL,
            grid_cd VARCHAR2(20) NOT NULL,
            sex_code NUMBER(1) NOT NULL,
            sex_label VARCHAR2(10 CHAR) NOT NULL,
            aligned_age_order NUMBER(2) NOT NULL,
            aligned_age_group VARCHAR2(30 CHAR) NOT NULL,
            model_age_code NUMBER(2),
            model_age_label VARCHAR2(30 CHAR),
            model_applicable CHAR(1) NOT NULL,
            alignment_status VARCHAR2(40 CHAR) NOT NULL,
            alignment_note VARCHAR2(200 CHAR) NOT NULL,
            source_age_groups VARCHAR2(100 CHAR) NOT NULL,
            source_age_group_count NUMBER(2) NOT NULL,
            target_population_est NUMBER(19) NOT NULL,
            proxy_flag CHAR(1) DEFAULT 'Y' NOT NULL,
            overlap_adjusted CHAR(1) DEFAULT 'N' NOT NULL,
            estimate_method VARCHAR2(300 CHAR) NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_GRID_TARGET_SEX_AGE PRIMARY KEY (
                etl_run_id, grid_cd, sex_code, aligned_age_order
            ),
            CONSTRAINT FK_GRID_TARGET_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT FK_GRID_TARGET_GRID FOREIGN KEY (grid_cd)
                REFERENCES DIM_GRID (grid_cd),
            CONSTRAINT CK_GRID_TARGET_SEX CHECK (sex_code IN (1, 2)),
            CONSTRAINT CK_GRID_TARGET_AGE CHECK (
                aligned_age_order BETWEEN 0 AND 8
                AND (model_age_code IS NULL OR model_age_code BETWEEN 1 AND 7)
            ),
            CONSTRAINT CK_GRID_TARGET_FLAGS CHECK (
                model_applicable IN ('Y', 'N')
                AND proxy_flag IN ('Y', 'N')
                AND overlap_adjusted IN ('Y', 'N')
            ),
            CONSTRAINT CK_GRID_TARGET_VALUE CHECK (target_population_est >= 0)
        )
    """,
    "FACT_PREF_SEX_AGE": """
        CREATE TABLE FACT_PREF_SEX_AGE (
            etl_run_id NUMBER NOT NULL,
            reference_year NUMBER(4) NOT NULL,
            sex_code NUMBER(1) NOT NULL,
            sex_label VARCHAR2(10 CHAR) NOT NULL,
            age_code NUMBER(2) NOT NULL,
            age_label VARCHAR2(30 CHAR) NOT NULL,
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            absolute_probability NUMBER(20, 15) NOT NULL,
            other_probability NUMBER(20, 15) NOT NULL,
            conditional_share NUMBER(20, 15),
            policy_flag CHAR(1) NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_PREF_SEX_AGE PRIMARY KEY (
                etl_run_id, sex_code, age_code, category_code
            ),
            CONSTRAINT FK_PREF_SEX_AGE_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT FK_PREF_SEX_AGE_CAT FOREIGN KEY (
                scheme_code, category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT CK_PREF_SEX_AGE_CODES CHECK (
                sex_code IN (1, 2) AND age_code BETWEEN 1 AND 7
            ),
            CONSTRAINT CK_PREF_SEX_AGE_VALUES CHECK (
                absolute_probability BETWEEN 0 AND 1
                AND other_probability BETWEEN 0 AND 1
                AND (conditional_share IS NULL OR conditional_share BETWEEN 0 AND 1)
                AND policy_flag IN ('Y', 'N')
            )
        )
    """,
    "FACT_GRID_PREF_DEMAND": """
        CREATE TABLE FACT_GRID_PREF_DEMAND (
            etl_run_id NUMBER NOT NULL,
            reference_year NUMBER(4) NOT NULL,
            grid_cd VARCHAR2(20) NOT NULL,
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            target_population_est NUMBER(24, 12) NOT NULL,
            absolute_probability NUMBER(20, 15),
            potential_demand NUMBER(24, 12) NOT NULL,
            other_probability NUMBER(20, 15),
            other_potential_demand NUMBER(24, 12) NOT NULL,
            conditional_share NUMBER(20, 15),
            estimate_flag CHAR(1) NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_GRID_PREF_DEMAND PRIMARY KEY (
                etl_run_id, grid_cd, category_code
            ),
            CONSTRAINT FK_GRID_PREF_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT FK_GRID_PREF_GRID FOREIGN KEY (grid_cd)
                REFERENCES DIM_GRID (grid_cd),
            CONSTRAINT FK_GRID_PREF_CAT FOREIGN KEY (
                scheme_code, category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT CK_GRID_PREF_VALUES CHECK (
                target_population_est >= 0
                AND potential_demand >= 0
                AND other_potential_demand >= 0
                AND (absolute_probability IS NULL OR absolute_probability BETWEEN 0 AND 1)
                AND (other_probability IS NULL OR other_probability BETWEEN 0 AND 1)
                AND (conditional_share IS NULL OR conditional_share BETWEEN 0 AND 1)
                AND estimate_flag IN ('Y', 'N')
            )
        )
    """,
    "FACT_GRID_ACCESSIBILITY": """
        CREATE TABLE FACT_GRID_ACCESSIBILITY (
            etl_run_id NUMBER NOT NULL,
            target_reference_year NUMBER(4) NOT NULL,
            merchant_snapshot_date DATE NOT NULL,
            method_code VARCHAR2(40) NOT NULL,
            demand_basis VARCHAR2(40) NOT NULL,
            access_mode_code VARCHAR2(10) NOT NULL,
            grid_cd VARCHAR2(20) NOT NULL,
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            accessibility_score NUMBER(38, 20) NOT NULL,
            accessible_merchant_count NUMBER(10) NOT NULL,
            target_population_est NUMBER(24, 12) NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_GRID_ACCESS PRIMARY KEY (
                etl_run_id, access_mode_code, grid_cd, category_code
            ),
            CONSTRAINT FK_GRID_ACCESS_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT FK_GRID_ACCESS_GRID FOREIGN KEY (grid_cd)
                REFERENCES DIM_GRID (grid_cd),
            CONSTRAINT FK_GRID_ACCESS_CAT FOREIGN KEY (
                scheme_code, category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT CK_GRID_ACCESS_VALUES CHECK (
                access_mode_code IN ('WALK', 'TRANSIT')
                AND demand_basis = 'TARGET_POPULATION_UNWEIGHTED'
                AND accessibility_score >= 0
                AND accessible_merchant_count >= 0
                AND target_population_est >= 0
            )
        )
    """,
    "FACT_FACILITY_ACCESS_RATIO": """
        CREATE TABLE FACT_FACILITY_ACCESS_RATIO (
            etl_run_id NUMBER NOT NULL,
            target_reference_year NUMBER(4) NOT NULL,
            merchant_snapshot_date DATE NOT NULL,
            method_code VARCHAR2(40) NOT NULL,
            demand_basis VARCHAR2(40) NOT NULL,
            access_mode_code VARCHAR2(10) NOT NULL,
            merchant_source_id VARCHAR2(30) NOT NULL,
            scheme_code VARCHAR2(30) NOT NULL,
            category_code VARCHAR2(30) NOT NULL,
            effective_demand NUMBER(38, 20) NOT NULL,
            facility_name VARCHAR2(200 CHAR) NOT NULL,
            district_name VARCHAR2(100 CHAR) NOT NULL,
            subcategory_name VARCHAR2(100 CHAR) NOT NULL,
            supply_quantity NUMBER(20, 8) NOT NULL,
            supply_demand_ratio NUMBER(38, 20) NOT NULL,
            loaded_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_FACILITY_ACCESS PRIMARY KEY (
                etl_run_id, access_mode_code,
                merchant_source_id, category_code
            ),
            CONSTRAINT FK_FACILITY_ACCESS_RUN FOREIGN KEY (etl_run_id)
                REFERENCES META_ETL_RUN (etl_run_id),
            CONSTRAINT FK_FACILITY_ACCESS_CAT FOREIGN KEY (
                scheme_code, category_code
            ) REFERENCES DIM_CATEGORY (scheme_code, category_code),
            CONSTRAINT CK_FACILITY_ACCESS_VALUES CHECK (
                access_mode_code IN ('WALK', 'TRANSIT')
                AND demand_basis = 'TARGET_POPULATION_UNWEIGHTED'
                AND effective_demand >= 0
                AND supply_quantity >= 0
                AND supply_demand_ratio >= 0
            )
        )
    """,
}


VIEW_DDL: dict[str, str] = {
    "VW_CARD_GU_CAT": """
        CREATE OR REPLACE VIEW VW_CARD_GU_CAT AS
        SELECT
            f.reference_year,
            f.district_code,
            a.area_name AS district_name,
            f.scheme_code,
            f.category_code,
            c.category_name,
            f.usage_amount_won,
            f.usage_count,
            y.issued_card_count,
            y.issued_amount_won,
            y.used_amount_won,
            CASE
                WHEN y.issued_amount_won > 0
                THEN y.used_amount_won / y.issued_amount_won * 100
            END AS issued_utilization_pct,
            CASE
                WHEN y.used_amount_won > 0
                THEN f.usage_amount_won / y.used_amount_won * 100
            END AS category_amount_share_pct,
            CASE
                WHEN y.usage_count > 0
                THEN f.usage_count / y.usage_count * 100
            END AS category_count_share_pct
        FROM FACT_CARD_GU_CAT f
        JOIN FACT_CARD_GU_YEAR y
          ON y.reference_year = f.reference_year
         AND y.district_code = f.district_code
        JOIN DIM_ADMIN_AREA a
          ON a.area_code = f.district_code
        JOIN DIM_CATEGORY c
          ON c.scheme_code = f.scheme_code
         AND c.category_code = f.category_code
    """,
    "VW_GRID_TARGET_MODEL_INPUT": """
        CREATE OR REPLACE VIEW VW_GRID_TARGET_MODEL_INPUT AS
        SELECT
            f.grid_cd,
            gu.area_name AS district_name,
            dong.area_name AS dong_name,
            f.sex_code,
            f.sex_label,
            f.aligned_age_order,
            f.aligned_age_group,
            f.model_age_code,
            f.model_age_label,
            f.model_applicable,
            f.alignment_status,
            f.alignment_note,
            f.source_age_groups,
            f.source_age_group_count,
            f.target_population_est,
            f.reference_year,
            f.proxy_flag,
            f.overlap_adjusted,
            f.estimate_method,
            f.etl_run_id
        FROM FACT_GRID_TARGET_SEX_AGE f
        JOIN DIM_GRID g ON g.grid_cd = f.grid_cd
        JOIN DIM_ADMIN_AREA dong ON dong.area_code = g.dong_code
        JOIN DIM_ADMIN_AREA gu ON gu.area_code = dong.parent_area_code
        WHERE f.model_applicable = 'Y'
          AND f.etl_run_id = (
              SELECT MAX(r.etl_run_id)
              FROM META_ETL_RUN r
              WHERE r.pipeline_name = 'grid_target_population_2024_v1'
                AND r.status = 'SUCCESS'
        )
    """,
    "VW_GRID_PREF_DEMAND": """
        CREATE OR REPLACE VIEW VW_GRID_PREF_DEMAND AS
        SELECT
            f.reference_year,
            f.grid_cd,
            g.dong_code,
            dong.area_name AS dong_name,
            gu.area_code AS district_code,
            gu.area_name AS district_name,
            f.scheme_code,
            f.category_code,
            c.category_name,
            f.target_population_est,
            f.absolute_probability,
            f.potential_demand,
            f.other_probability,
            f.other_potential_demand,
            f.conditional_share,
            f.estimate_flag,
            f.etl_run_id
        FROM FACT_GRID_PREF_DEMAND f
        JOIN DIM_GRID g ON g.grid_cd = f.grid_cd
        JOIN DIM_ADMIN_AREA dong ON dong.area_code = g.dong_code
        JOIN DIM_ADMIN_AREA gu ON gu.area_code = dong.parent_area_code
        JOIN DIM_CATEGORY c
          ON c.scheme_code = f.scheme_code
         AND c.category_code = f.category_code
        WHERE f.etl_run_id = (
            SELECT MAX(r.etl_run_id)
            FROM META_ETL_RUN r
            WHERE r.pipeline_name = 'preference_spatial_2024_v1'
              AND r.status = 'SUCCESS'
        )
    """,
    "VW_DONG_PREF_DEMAND": """
        CREATE OR REPLACE VIEW VW_DONG_PREF_DEMAND AS
        SELECT
            reference_year, dong_code, dong_name, district_code, district_name,
            scheme_code, category_code, category_name,
            target_population_est,
            CASE WHEN target_population_est > 0
                 THEN potential_demand / target_population_est END
                AS absolute_probability,
            potential_demand,
            CASE WHEN target_population_est > 0
                 THEN other_potential_demand / target_population_est END
                AS other_probability,
            other_potential_demand,
            CASE WHEN policy_demand_total > 0
                 THEN potential_demand / policy_demand_total END
                AS conditional_share,
            etl_run_id
        FROM (
            SELECT grouped.*,
                   SUM(potential_demand) OVER (
                       PARTITION BY etl_run_id, dong_code
                   ) AS policy_demand_total
            FROM (
                SELECT reference_year, dong_code, dong_name,
                       district_code, district_name, scheme_code,
                       category_code, category_name,
                       SUM(target_population_est) AS target_population_est,
                       SUM(potential_demand) AS potential_demand,
                       SUM(other_potential_demand) AS other_potential_demand,
                       etl_run_id
                FROM VW_GRID_PREF_DEMAND
                GROUP BY reference_year, dong_code, dong_name,
                         district_code, district_name, scheme_code,
                         category_code, category_name, etl_run_id
            ) grouped
        )
    """,
    "VW_GU_PREF_DEMAND": """
        CREATE OR REPLACE VIEW VW_GU_PREF_DEMAND AS
        SELECT
            reference_year, district_code, district_name,
            scheme_code, category_code, category_name,
            target_population_est,
            CASE WHEN target_population_est > 0
                 THEN potential_demand / target_population_est END
                AS absolute_probability,
            potential_demand,
            CASE WHEN target_population_est > 0
                 THEN other_potential_demand / target_population_est END
                AS other_probability,
            other_potential_demand,
            CASE WHEN policy_demand_total > 0
                 THEN potential_demand / policy_demand_total END
                AS conditional_share,
            etl_run_id
        FROM (
            SELECT grouped.*,
                   SUM(potential_demand) OVER (
                       PARTITION BY etl_run_id, district_code
                   ) AS policy_demand_total
            FROM (
                SELECT reference_year, district_code, district_name,
                       scheme_code, category_code, category_name,
                       SUM(target_population_est) AS target_population_est,
                       SUM(potential_demand) AS potential_demand,
                       SUM(other_potential_demand) AS other_potential_demand,
                       etl_run_id
                FROM VW_GRID_PREF_DEMAND
                GROUP BY reference_year, district_code, district_name,
                         scheme_code, category_code, category_name, etl_run_id
            ) grouped
        )
    """,
    "VW_GRID_ACCESSIBILITY": """
        CREATE OR REPLACE VIEW VW_GRID_ACCESSIBILITY AS
        SELECT
            f.target_reference_year,
            f.merchant_snapshot_date,
            f.method_code,
            f.demand_basis,
            f.access_mode_code,
            CASE f.access_mode_code
                WHEN 'WALK' THEN '도보'
                WHEN 'TRANSIT' THEN '대중교통'
            END AS access_mode_name,
            f.grid_cd,
            g.dong_code,
            dong.area_name AS dong_name,
            gu.area_code AS district_code,
            gu.area_name AS district_name,
            f.scheme_code,
            f.category_code,
            c.category_name,
            f.accessibility_score,
            f.accessible_merchant_count,
            f.target_population_est,
            f.etl_run_id
        FROM FACT_GRID_ACCESSIBILITY f
        JOIN DIM_GRID g ON g.grid_cd = f.grid_cd
        JOIN DIM_ADMIN_AREA dong ON dong.area_code = g.dong_code
        JOIN DIM_ADMIN_AREA gu ON gu.area_code = dong.parent_area_code
        JOIN DIM_CATEGORY c
          ON c.scheme_code = f.scheme_code
         AND c.category_code = f.category_code
        WHERE f.etl_run_id = (
            SELECT MAX(r.etl_run_id)
            FROM META_ETL_RUN r
            WHERE r.pipeline_name = 'h3sfca_accessibility_baseline_v1'
              AND r.status = 'SUCCESS'
        )
    """,
}


READ_OBJECTS = (
    "META_SOURCE_FILE",
    "META_ETL_RUN",
    "META_ETL_RUN_INPUT",
    "DIM_ADMIN_AREA",
    "DIM_GRID",
    "DIM_CATEGORY",
    "BRIDGE_CATEGORY_MAP",
    "FACT_CARD_GU_YEAR",
    "FACT_CARD_GU_CAT",
    "FACT_CARD_GU_SEX",
    "FACT_CARD_GU_AGE",
    "DIM_MERCHANT_SNAPSHOT",
    "FACT_GRID_TARGET_SEX_AGE",
    "FACT_PREF_SEX_AGE",
    "FACT_GRID_PREF_DEMAND",
    "FACT_GRID_ACCESSIBILITY",
    "FACT_FACILITY_ACCESS_RATIO",
    "VW_CARD_GU_CAT",
    "VW_GRID_TARGET_MODEL_INPUT",
    "VW_GRID_PREF_DEMAND",
    "VW_DONG_PREF_DEMAND",
    "VW_GU_PREF_DEMAND",
    "VW_GRID_ACCESSIBILITY",
)


CARD_YEAR_DETAIL_COLUMNS: dict[str, str] = {
    "USER_COUNT": "NUMBER(19)",
    "CULTURE_EXP_COUNT": "NUMBER(19)",
    "CULTURE_EXP_PCT": "NUMBER(12, 8)",
}


def validate_identifier(value: str) -> str:
    """Oracle 프로젝트 객체 이름을 안전한 대문자 식별자로 검증한다."""

    normalized = value.strip().upper()
    if not _IDENTIFIER_PATTERN.fullmatch(normalized):
        raise ValueError(
            "Oracle 식별자는 영문자로 시작하는 1~30자의 "
            "영문 대문자·숫자·_·$·# 조합이어야 합니다."
        )
    return normalized


def validate_app_password(password: str, username: str = APP_SCHEMA) -> None:
    """ADB 사용자 생성 전에 명백한 비밀번호 오류를 차단한다."""

    if not 12 <= len(password) <= 30:
        raise ValueError("비밀번호는 12~30자여야 합니다.")
    if '"' in password or any(character.isspace() for character in password):
        raise ValueError("비밀번호에는 큰따옴표나 공백을 사용할 수 없습니다.")
    if not any(character.isupper() for character in password):
        raise ValueError("비밀번호에는 영문 대문자가 하나 이상 필요합니다.")
    if not any(character.islower() for character in password):
        raise ValueError("비밀번호에는 영문 소문자가 하나 이상 필요합니다.")
    if not any(character.isdigit() for character in password):
        raise ValueError("비밀번호에는 숫자가 하나 이상 필요합니다.")
    if username.upper() in password.upper():
        raise ValueError("비밀번호에는 사용자 이름을 포함할 수 없습니다.")


def _fetch_exists(cursor: Any, query: str, name: str) -> bool:
    cursor.execute(query, name=validate_identifier(name))
    return cursor.fetchone() is not None


def bootstrap_admin_objects(connection: Any, app_password: str) -> dict[str, Any]:
    """ADMIN 연결로 역할과 MNC_APP 계정을 멱등 생성한다."""

    validate_app_password(app_password)
    created_roles: list[str] = []
    with connection.cursor() as cursor:
        for role in (READ_ROLE, ETL_ROLE):
            exists = _fetch_exists(
                cursor,
                "SELECT 1 FROM dba_roles WHERE role = :name",
                role,
            )
            if not exists:
                cursor.execute(f"CREATE ROLE {validate_identifier(role)}")
                created_roles.append(role)

        user_exists = _fetch_exists(
            cursor,
            "SELECT 1 FROM dba_users WHERE username = :name",
            APP_SCHEMA,
        )
        if not user_exists:
            cursor.execute(
                f'CREATE USER {APP_SCHEMA} IDENTIFIED BY "{app_password}" '
                "DEFAULT TABLESPACE DATA QUOTA UNLIMITED ON DATA"
            )
        else:
            cursor.execute(f"ALTER USER {APP_SCHEMA} QUOTA UNLIMITED ON DATA")

        cursor.execute(
            "GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, "
            f"CREATE SEQUENCE, CREATE PROCEDURE TO {APP_SCHEMA}"
        )
        cursor.execute(f"GRANT {READ_ROLE} TO {ETL_ROLE}")

    return {
        "created_roles": created_roles,
        "app_user_created": not user_exists,
        "app_user": APP_SCHEMA,
    }


def bootstrap_app_schema(connection: Any) -> dict[str, Any]:
    """MNC_APP 연결로 누락 테이블과 조회 View를 생성한다."""

    created_tables: list[str] = []
    with connection.cursor() as cursor:
        for table_name, ddl in TABLE_DDL.items():
            exists = _fetch_exists(
                cursor,
                "SELECT 1 FROM user_tables WHERE table_name = :name",
                table_name,
            )
            if not exists:
                cursor.execute(ddl)
                created_tables.append(table_name)

        for ddl in VIEW_DDL.values():
            cursor.execute(ddl)

        for object_name in READ_OBJECTS:
            cursor.execute(f"GRANT SELECT ON {object_name} TO {READ_ROLE}")

        for table_name in TABLE_DDL:
            cursor.execute(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} "
                f"TO {ETL_ROLE}"
            )

    return {
        "created_tables": created_tables,
        "table_count": len(TABLE_DDL),
        "views_replaced": list(VIEW_DDL),
    }


def ensure_card_usage_detail_schema(connection: Any) -> dict[str, Any]:
    """초기 카드 테이블에 성별·연령·이용자 상세 구조를 안전하게 추가한다."""

    added_columns: list[str] = []
    created_tables: list[str] = []
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name FROM user_tab_columns
            WHERE table_name = 'FACT_CARD_GU_YEAR'
            """
        )
        existing_columns = {str(row[0]).upper() for row in cursor.fetchall()}
        for column_name, data_type in CARD_YEAR_DETAIL_COLUMNS.items():
            if column_name not in existing_columns:
                cursor.execute(
                    f"ALTER TABLE FACT_CARD_GU_YEAR ADD ({column_name} {data_type})"
                )
                added_columns.append(column_name)

        for table_name in ("FACT_CARD_GU_SEX", "FACT_CARD_GU_AGE"):
            exists = _fetch_exists(
                cursor,
                "SELECT 1 FROM user_tables WHERE table_name = :name",
                table_name,
            )
            if not exists:
                cursor.execute(TABLE_DDL[table_name])
                created_tables.append(table_name)
            cursor.execute(f"GRANT SELECT ON {table_name} TO {READ_ROLE}")
            cursor.execute(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO {ETL_ROLE}"
            )

    return {
        "added_columns": added_columns,
        "created_tables": created_tables,
    }


def ensure_merchant_schema(connection: Any) -> dict[str, Any]:
    """기존 MNC_APP에 가맹점 snapshot 테이블을 멱등 추가한다."""

    created_tables: list[str] = []
    table_name = "DIM_MERCHANT_SNAPSHOT"
    with connection.cursor() as cursor:
        exists = _fetch_exists(
            cursor,
            "SELECT 1 FROM user_tables WHERE table_name = :name",
            table_name,
        )
        if not exists:
            cursor.execute(TABLE_DDL[table_name])
            created_tables.append(table_name)
        cursor.execute(f"GRANT SELECT ON {table_name} TO {READ_ROLE}")
        cursor.execute(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO {ETL_ROLE}"
        )
    return {"created_tables": created_tables}


def ensure_grid_population_schema(connection: Any) -> dict[str, Any]:
    """기존 MNC_APP에 격자·성연령 대상자 테이블과 View를 멱등 추가한다."""

    created_tables: list[str] = []
    table_names = ("DIM_GRID", "FACT_GRID_TARGET_SEX_AGE")
    with connection.cursor() as cursor:
        for table_name in table_names:
            exists = _fetch_exists(
                cursor,
                "SELECT 1 FROM user_tables WHERE table_name = :name",
                table_name,
            )
            if not exists:
                cursor.execute(TABLE_DDL[table_name])
                created_tables.append(table_name)
            cursor.execute(f"GRANT SELECT ON {table_name} TO {READ_ROLE}")
            cursor.execute(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO {ETL_ROLE}"
            )
        cursor.execute(VIEW_DDL["VW_GRID_TARGET_MODEL_INPUT"])
        cursor.execute(
            "GRANT SELECT ON VW_GRID_TARGET_MODEL_INPUT TO MNC_READ_ROLE"
        )
    return {
        "created_tables": created_tables,
        "views_replaced": ["VW_GRID_TARGET_MODEL_INPUT"],
    }


def ensure_preference_schema(connection: Any) -> dict[str, Any]:
    """기존 MNC_APP에 선호확률·격자수요 테이블과 집계 View를 멱등 추가한다."""

    created_tables: list[str] = []
    table_names = ("FACT_PREF_SEX_AGE", "FACT_GRID_PREF_DEMAND")
    view_names = (
        "VW_GRID_PREF_DEMAND",
        "VW_DONG_PREF_DEMAND",
        "VW_GU_PREF_DEMAND",
    )
    with connection.cursor() as cursor:
        for table_name in table_names:
            exists = _fetch_exists(
                cursor,
                "SELECT 1 FROM user_tables WHERE table_name = :name",
                table_name,
            )
            if not exists:
                cursor.execute(TABLE_DDL[table_name])
                created_tables.append(table_name)
            cursor.execute(f"GRANT SELECT ON {table_name} TO {READ_ROLE}")
            cursor.execute(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO {ETL_ROLE}"
            )
        for view_name in view_names:
            cursor.execute(VIEW_DDL[view_name])
            cursor.execute(f"GRANT SELECT ON {view_name} TO {READ_ROLE}")
    return {"created_tables": created_tables, "views_replaced": list(view_names)}


def ensure_accessibility_schema(connection: Any) -> dict[str, Any]:
    """기존 H3SFCA 기준결과 테이블과 조회 View를 멱등 추가한다."""

    created_tables: list[str] = []
    table_names = ("FACT_GRID_ACCESSIBILITY", "FACT_FACILITY_ACCESS_RATIO")
    view_name = "VW_GRID_ACCESSIBILITY"
    with connection.cursor() as cursor:
        for table_name in table_names:
            exists = _fetch_exists(
                cursor,
                "SELECT 1 FROM user_tables WHERE table_name = :name",
                table_name,
            )
            if not exists:
                cursor.execute(TABLE_DDL[table_name])
                created_tables.append(table_name)
            cursor.execute(f"GRANT SELECT ON {table_name} TO {READ_ROLE}")
            cursor.execute(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO {ETL_ROLE}"
            )
        cursor.execute(VIEW_DDL[view_name])
        cursor.execute(f"GRANT SELECT ON {view_name} TO {READ_ROLE}")
    return {"created_tables": created_tables, "views_replaced": [view_name]}


def bootstrap_plan() -> dict[str, Any]:
    """접속 없이 생성 대상을 확인할 수 있는 계획을 반환한다."""

    return {
        "app_user": APP_SCHEMA,
        "roles": [READ_ROLE, ETL_ROLE],
        "tables": list(TABLE_DDL),
        "views": list(VIEW_DDL),
        "note": "기존 사용자와 테이블은 삭제하거나 덮어쓰지 않습니다.",
    }
